const SIMPLE_ACTION = 'SIMPLE_ACTION';
const SEARCH = 'SEARCH';
const TOGGLE_MODAL = 'TOGGLE_MODAL';
const FILTER_ALLERGEN = 'FILTER_ALLERGEN';

export default {
  SIMPLE_ACTION, SEARCH, TOGGLE_MODAL, FILTER_ALLERGEN,
};
